# Generated by Django 2.2.4 on 2019-08-24 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusquedaModel',
            fields=[
                ('id_busqueda', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('ands', models.CharField(blank=True, max_length=250)),
                ('phrase', models.CharField(blank=True, max_length=250)),
                ('ors', models.CharField(blank=True, max_length=250)),
                ('nots', models.CharField(blank=True, max_length=250)),
                ('tags', models.CharField(blank=True, max_length=250)),
                ('respondiendo', models.CharField(blank=True, max_length=250)),
                ('mencionando', models.CharField(blank=True, max_length=250)),
                ('From', models.CharField(blank=True, max_length=250)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('fecha_peticion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('finalizado', models.BooleanField(default=False)),
            ],
        ),
    ]
