# Generated by Django 2.2.4 on 2019-09-21 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busquedamodel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='busquedamodel',
            name='tiene_tweets',
        ),
        migrations.AddField(
            model_name='busquedamodel',
            name='es_cuenta',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='busquedamodel',
            name='nombre',
            field=models.CharField(default='nombre', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busquedamodel',
            name='fecha_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='busquedamodel',
            name='fecha_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='busquedamodel',
            name='fecha_peticion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='busquedamodel',
            name='id_busqueda',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
