# Generated by Django 2.2.4 on 2019-08-24 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('busqueda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busquedamodel',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='busquedamodel',
            name='fecha_peticion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
