# Generated by Django 2.2.4 on 2019-09-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TweetsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=250)),
                ('text', models.CharField(blank=True, max_length=350)),
                ('fecha', models.DateTimeField()),
                ('likes', models.IntegerField()),
                ('replies', models.IntegerField()),
                ('rts', models.IntegerField()),
                ('url', models.CharField(blank=True, max_length=250)),
                ('label', models.CharField(blank=True, max_length=250)),
                ('id_busqueda', models.IntegerField()),
                ('nube', models.CharField(blank=True, max_length=350)),
            ],
        ),
    ]
