# Generated by Django 2.2.4 on 2019-09-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetsmodel',
            name='text',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
