# Generated by Django 2.2.4 on 2019-09-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweetsmodel_id_busqueda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetsmodel',
            old_name='favs',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='tweetsmodel',
            old_name='link',
            new_name='url',
        ),
        migrations.AddField(
            model_name='tweetsmodel',
            name='nube',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AddField(
            model_name='tweetsmodel',
            name='replies',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
